title: Turntable
description: Turntable is a Sass library made to freshen up your workflow.
copyright: Copyright 2018

contact:
  author: Daniel Blake
  email: daniel@danielblake.design
  phone: 1-971-801-0208
  address: Portland, OR

same:
  github: https://github.com/dmbdesignpdx/turntable-kit
  npm: https://www.npmjs.com/package/turntable-kit

images:
  main: "turntable-main.gif"

colors:
  theme: 8338EC
  bkg: 8338EC
  tile: 000000

baseurl: ""
url: ""

kramdown:
  auto_ids: false
  syntax_highlighter: rouge

sass:
  style: compressed

port: 5000

exclude:
  - .sass-cache
  - .jekyll-metadata
  - .gitignore
  - .eslintrc.yml
  - .channel.json
  - node_modules
  - src
  - dist
  - package.json
  - gulpfile.js
  - README.md
  - LICENSE.md
  - yarn.lock

include:
  - _pages

defaults:
  -
    scope:
      path: "_pages"
    values:
      layout: "page"
